// Feather disable all

#macro INPUT_TOUCH_VERSION "1.1.0"
#macro INPUT_TOUCH_TARGET_VERISON "10.0"
#macro INPUT_TOUCH_DATE "2026-06-29"

#macro INPUT_TOUCH_VK_CLOSED 0
#macro INPUT_TOUCH_VK_CLOSING 1
#macro INPUT_TOUCH_VK_OPENED 2
#macro INPUT_TOUCH_VK_OPENING 3